apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-booking
  namespace: taxi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taxi-booking
  template:
    metadata:
      labels:
        app: taxi-booking
    spec:
      containers:
      - name: taxi-booking
        image: 717292228966.dkr.ecr.us-east-1.amazonaws.com/taxi-booking-app:v1.37
        imagePullPolicy: Always
        ports:
        - containerPort: 8080